### ISSUE TITLE
export result to file?

### ISSUE THREAD

**Issue by bientt210** [feinoujc/gh-search-cli#131]
Hi You,

I have a file (example: list.txt) and have a list of word in there, so how can i find sequentially base on that file. What should i do?
Can you help me.

Thanks you very much,
Have a nice day.

**Comment by feinoujc** [comment]
Hi @bientt210, are you asking how to search for a word in a file?

something like this? (find files with name list.txt that have the word hello in them)

```sh
~ ghs code --in file --filename=list.txt "hello"
```

**Comment by bientt210** [comment]
> Hi @bientt210, are you asking how to search for a word in a file?
> 
> something like this? (find files with name list.txt that have the word hello in them)
> 
> ```shell
> ~ ghs code --in file --filename=list.txt "hello"
> ```

Thanks for answer,

I mean, i have many words example: hello, hello1, hello2, hello3 ... in a filename was called list.txt so I want to search that words sequentially? how should i do?

Thanks you and  appreciate your help

**Comment by feinoujc** [comment]
I guess you can do “hello AND hello2” etc in the query. not sure what you mean by sequentially or how to get the api to do that
